#!/bin/bash
#SBATCH --job-name=ultrarefiner_phase2_hybrid
#SBATCH --output=logs/phase2_sam_hybrid_%j.out
#SBATCH --error=logs/phase2_sam_hybrid_%j.err
#SBATCH --partition=nvidia
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=16
#SBATCH --mem=192G
#SBATCH --time=90:00:00

# Print job information
echo "Job ID: $SLURM_JOB_ID"
echo "Job Name: $SLURM_JOB_NAME"
echo "Node: $SLURM_NODELIST"
echo "Start Time: $(date)"
echo "Working Directory: $(pwd)"
echo ""

# Activate conda environment
echo "Activating conda environment..."
source $(conda info --base)/etc/profile.d/conda.sh
conda activate /scratch/ll5582/3DSAM/envs/ultrarefiner  # Update this path
module load cuda/12.2.0

if [ $? -ne 0 ]; then
    echo "Error: Failed to activate conda environment"
    exit 1
fi

echo "Conda environment activated successfully"
echo "Python path: $(which python)"
echo ""

# Change to working directory
cd /scratch/ll5582/3DSAM/UltraRefiner  # Update this path
echo "Changed to directory: $(pwd)"
echo ""

mkdir -p logs

# ============================================================================
# Phase 2: Finetune SAM with Hybrid Data (Real + Augmented)
# ============================================================================
echo "Starting Phase 2: SAM Finetuning with Hybrid Data..."
echo ""

# Configuration
GT_DATA_ROOT="./dataset/processed"
PRED_DATA_ROOT="./dataset/transunet_preds"  # Generated by generate_transunet_predictions.py
DATASETS="BUSI BUSBRA BUS BUS_UC BUS_UCLM"
SAM_CHECKPOINT="./pretrained/sam_vit_b_01ec64.pth"
SAM_MODEL_TYPE="vit_b"
OUTPUT_DIR="./checkpoints/sam_finetuned_hybrid"

# Training parameters
EPOCHS=300
BATCH_SIZE=8
LR=1e-4
NUM_WORKERS=16

# Hybrid ratio: how much real TransUNet predictions vs augmented GT
REAL_RATIO=0.5  # 50% real predictions, 50% augmented GT

# Speed optimizations
USE_AMP="--use_amp"
GRAD_ACCUM_STEPS=1
PREFETCH_FACTOR=8
FAST_SOFT_MASK="--fast_soft_mask"

# Augmentation for GT masks
AUGMENTOR_PRESET="default"
SOFT_MASK_PROB=0.8
CHANGE_PENALTY_WEIGHT=0.5

# Phase 3 compatibility
TRANSUNET_IMG_SIZE=224
MASK_PROMPT_STYLE="direct"
USE_ROI_CROP="--use_roi_crop"
ROI_EXPAND_RATIO=0.5

# Optional: Resume from checkpoint
# RESUME_CHECKPOINT="./checkpoints/sam_finetuned_hybrid/BUSI_BUSBRA_BUS_BUS_UC_BUS_UCLM/best.pth"

echo "============================================================"
echo "Configuration:"
echo "============================================================"
echo "  GT data root: ${GT_DATA_ROOT}"
echo "  Pred data root: ${PRED_DATA_ROOT}"
echo "  Datasets: ${DATASETS}"
echo "  SAM checkpoint: ${SAM_CHECKPOINT}"
echo "  Output dir: ${OUTPUT_DIR}"
echo ""
echo "Hybrid Training:"
echo "  Real prediction ratio: ${REAL_RATIO} (${REAL_RATIO}x100% real, $((1-REAL_RATIO))x100% augmented)"
echo "  Epochs: ${EPOCHS}"
echo "  Batch size: ${BATCH_SIZE}"
echo "  Learning rate: ${LR}"
echo ""
echo "Speed Optimizations:"
echo "  Mixed Precision (AMP): enabled"
echo "  Fast soft mask: enabled"
echo "  Prefetch factor: ${PREFETCH_FACTOR}"
echo ""
echo "Phase 3 Compatibility:"
echo "  TransUNet img size: ${TRANSUNET_IMG_SIZE}"
echo "  Mask prompt style: ${MASK_PROMPT_STYLE}"
echo "  ROI cropping: enabled"
echo "  ROI expand ratio: ${ROI_EXPAND_RATIO}"
echo "============================================================"
echo ""

# Build command
CMD="python scripts/finetune_sam_hybrid.py \
    --gt_data_root ${GT_DATA_ROOT} \
    --pred_data_root ${PRED_DATA_ROOT} \
    --datasets ${DATASETS} \
    --real_ratio ${REAL_RATIO} \
    --sam_checkpoint ${SAM_CHECKPOINT} \
    --sam_model_type ${SAM_MODEL_TYPE} \
    --epochs ${EPOCHS} \
    --batch_size ${BATCH_SIZE} \
    --lr ${LR} \
    --num_workers ${NUM_WORKERS} \
    --augmentor_preset ${AUGMENTOR_PRESET} \
    --soft_mask_prob ${SOFT_MASK_PROB} \
    --change_penalty_weight ${CHANGE_PENALTY_WEIGHT} \
    --transunet_img_size ${TRANSUNET_IMG_SIZE} \
    --mask_prompt_style ${MASK_PROMPT_STYLE} \
    ${USE_ROI_CROP} \
    --roi_expand_ratio ${ROI_EXPAND_RATIO} \
    ${USE_AMP} \
    --grad_accum_steps ${GRAD_ACCUM_STEPS} \
    --prefetch_factor ${PREFETCH_FACTOR} \
    ${FAST_SOFT_MASK} \
    --output_dir ${OUTPUT_DIR}"

# Add resume flag if checkpoint exists
if [ -n "${RESUME_CHECKPOINT}" ] && [ -f "${RESUME_CHECKPOINT}" ]; then
    echo "Resuming from checkpoint: ${RESUME_CHECKPOINT}"
    CMD="${CMD} --resume ${RESUME_CHECKPOINT}"
fi

echo "Running command:"
echo "${CMD}"
echo ""

eval ${CMD}

if [ $? -eq 0 ]; then
    echo ""
    echo "============================================================"
    echo "Phase 2 SAM finetuning (hybrid data) completed!"
    echo "============================================================"
    echo "Checkpoints saved to: ${OUTPUT_DIR}/"
    echo "  - best.pth: Full refiner state (for resuming)"
    echo "  - best_sam.pth: SAM weights (for Phase 3)"
    echo ""
    echo "Hybrid Training Benefits:"
    echo "  - Real predictions capture actual TransUNet failure modes"
    echo "  - Augmented GT provides additional diversity and edge cases"
    echo "  - Ratio of ${REAL_RATIO} means ${REAL_RATIO}x100% real, $((1-REAL_RATIO))x100% augmented"
else
    echo ""
    echo "Phase 2 SAM finetuning failed with exit code $?"
    exit 1
fi

echo ""
echo "End Time: $(date)"
